= Number
:mdn-js-globals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

The `@perfective/common/number` package declares types and functions to work with real numbers,
including the JavaScript
`link:{mdn-js-globals}/Number[Number]` class.


== Number

* Nominal types:
** `PositiveNumber`
— a number that is greater than 0.
** `NonNegativeNumber`
– a number that is greater than or equal to 0.
** `NegativeNumber`
— a number that is less than 0.
** `NonPositiveNumber`
— a number that is less than or equal to 0.
+
* Type guards:
+
** `isNumber<T>(value: number | T): value is number`
— returns `true` if a given `value` is a number and not a `NaN`.
** `isNotNumber<T>(value: number | T): value is T`
— returns `true` if a given `value` is not a number or is a `NaN`.
+
* Functions:
+
** `negative(value: number): number`
— returns the negated value of a given number.
If the given number is 0, returns 0.
+
* `Number` methods:
+
** `exponential(fraction: Digits): Unary<number, string>`
— creates a function that returns the input number in exponential notation
rounded to a given number of `fraction` digits.
** `fixed(fraction: Digits): Unary<number, string>`
— creates a function that returns the input number in fixed-point notation with a given number of `fraction` digits.
** `precision(precision: Precision): Unary<number, string>`
— creates a function that returns the input number in fixed-point or exponential notation
rounded to a given `precision`.
+
[WARNING]
====
In JavaScript, a `Number` only keeps 17 decimal places of precision,
while `Digit` is an integer from `0` to `20`,
and `Precision` is an integer from `1` to `21`.
So passing digits or precision over 15 requires careful consideration and thorough testing.
====
+
* Arithmetic functions:
+
** `sum(augend: number, addend: number): number`
— returns the result of addition of the given numbers.
** `difference(minuend: number, subtrahend: number): number`
— returns the result of subtraction of a given `subtrahend` from a given `minuend`.
** `product(multiplier: number, multiplicand: number): number`
— returns the result of multiplication of given numbers.
** `quotient(dividend: number, divisor: number): number`
— returns the result of division of a given `dividend` by a given `divisor`.
** `remainder(dividend: number, divisor: number): number`.
— returns the remainder of division of a given `dividend` by a given `divisor`.
** `absolute(value: number): number`
— returns the absolute value of a given number.
+
Throws `Exception` if the given value is `NaN`.
+
* Rounding functions:
+
** `ceil(value: number): number`
— returns the smallest integer greater than or equal to a given number.
Returns `Infinity` if the given value is `Infinity`.
Returns `-Infinity` if the given value is `-Infinity`.
Throws `Exception` if the given value is `NaN`.
+
** `floatRound(value: number): number`
— returns the nearest 32-bit single precision float representation of a given number.
Throws `Exception` if the given value is `NaN`.
+
** `floor(value: number): number`
— returns the largest integer less than or equal to a given number.
Returns `Infinity` if the given value is `Infinity`.
Returns `-Infinity` if the given value is `-Infinity`.
Throws `Exception` if the given value is `NaN`.
+
** `round(value: number): number`
— rounds a floating-point number to the nearest integer.
Returns `Infinity` if the given value is `Infinity`.
Returns `-Infinity` if the given value is `-Infinity`.
Throws `Exception` if the given value is `NaN`.
+
** `truncated(value: number): number`
— returns the integer part of a floating-point number.
Throws `Exception` if the given value is `NaN`.
+
* Trigonometry types and functions:
+
** `Radians` is a nominal type for a radians value (`number`).
+
** `arccos(cosine: number): Radians | null`
— returns the inverse cosine [0, π] of the given cosine value [-1, 1].
+
Throws `Exception` if the given cosine is less than `-1`, greater than `1`, or is `NaN`.
** `arccosh(value: number): NonNegativeNumber | null`
— returns the inverse hyperbolic cosine [0, +∞) of a given number from [1, +∞).
+
Throws `Exception` if the given value is less than 1 or is `NaN`.
** `arcsin(sine: number): Radians | null`
— returns the inverse sine [-π/2, π/2] of the given sine value [-1, 1].
+
Throws `Exception` if the given sine is less than `-1`, greater than `1` or is `NaN`.
** `arcsinh(value: number): number`
— returns the inverse hyperbolic sine (-∞, +∞) of a given number from (-∞, +∞).
Throws `Exception` if the given value is `NaN`.
** `arctan(value: number): Radians`
— returns the inverse tangent [-π/2, π/2] of a given value from (-∞, +∞).
+
Throws `Exception` if the given value is `NaN`.
** `arctan2(y: number, x: number): Radians`
+
`arctan2([y, x]: [number, number]): Radians`
— returns the angle in radians [-π, π] between the positive x-axis and the ray from (0, 0) to the point (x, y).
+
Throws `Exception` if either `y` or `x` is `NaN`.
+
** `arctanh(value: number): number`
— returns the inverse hyperbolic tangent (-∞, +∞) of a given number from (-1, 1).
+
Throws `Exception` if the given value is less than or equal to -1, greater than or equal to 1, or is `NaN`.
+
** `cos(angle: Radians): number`
— returns the cosine [-1, 1] of a given angle in radians.
+
Throws `Exception` if the given angle is `NaN` or `Infinity`.
+
** `cosh(value: number): number`
— returns the hyperbolic cosine [1, +∞) of a given number.
+
Throws `Exception` if the given value is `NaN`.
+
** `sin(angle: Radians): number`
— returns the sine [-1, 1] of a given angle in radians.
+
Throws `Exception` if the given angle is `NaN` or `Infinity`.
+
** `sinh(value: number): number`
— returns the hyperbolic sine (-∞, +∞) of a given number.
+
Throws `Exception` if the given value is `NaN`.
+
** `tan(angle: number): number`
— returns the tangent (-∞, +∞) of a given angle in radians.
+
Throws `Exception` if the given angle is `NaN` or `Infinity`.
+
** `tanh(value: number): number`
— returns the hyperbolic tangent (-1, 1) of a given number.
+
Returns 1 if the given value is `Infinity`.
+
Returns -1 if the given value is `-Infinity`.
+
Throws `Exception` if the given value is `NaN`.
+
* Set functions:
+
** `maximum(values: readonly number[]): number | null`
— returns the largest of given numbers (ignores `NaN`).
If the given `values` array is empty or contains only `NaN`, returns `null`.
Use this function instead of `Math.max`, as it returns `Infinity` or `NaN` for edge cases.
+
** `minimum(values: readonly number[]): number | null`
— returns the smallest of given numbers (ignores `NaN`).
If the given `values` array is empty or contains only `NaN`, returns `null`.
Use this function instead of `Math.min`, as it returns `Infinity` or `NaN` for edge cases.


== Integer

* Nominal types (aliases of `number`):
** `Integer`
— a positive natural number, zero, and negative integer number.
** `SafeInteger`
— integers from `-(2^53 - 1)` to `2^53 - 1`, inclusive.
** `PositiveInteger`
— an integer that is greater than or equal to 0.
** `NonNegativeInteger`
— an integer that is greater than 0.
** `NonPositiveInteger`
— an integer that is less than or equal to 0.
** `NegativeInteger`.
— an integer that is less than 0.
+
* Predicates:
** `isInteger(value: number): value is Integer`
— returns `true` if a given number is an integer.
** `isSafeInteger(value: number): value is SafeInteger`
— returns `true` if a given number is from `-(2^53 - 1)` to `2^53 - 1`, inclusive.
** `isNonNegativeInteger(value: number): value is NonNegativeInteger`
— returns `true` if a given number is an integer and is greater than or equal to 0.
** `isPositiveInteger(value: number): value is PositiveInteger`
— returns `true` if a given number is an integer and is greater than 0.
** `isNonPositiveInteger(value: number): value is NonPositiveInteger`
— returns `true` if a given number is an integer and is less than or equal to 0.
** `isNegativeInteger(value: number): value is NegativeInteger`
— returns `true` if a given number is an integer and is less than 0.


== Natural

* Nominal types (aliases of `number`):
+
** `Natural`
— a non-negative integer, according to the ISO 80000-2.
+
* Type Guards:
+
** `isNatural<T>(value: number | T): value is Natural`.
— returns `true` if a given number is a non-negative integer.


== Infinity

* Nominal types:
+
** `Infinity`
— either a `PositiveInfinity` or `NegativeInfinity`.
** `PositiveInfinity`
— an alias for a `number` signifying `Number.POSITIVE_INFINITY`.
** `NegativeInfinity`
— an alias for a `number` signifying `Number.NEGATIVE_INFINITY`.
+
* Predicates:
+
** `isInfinity(value: number): boolean`
— returns `true` if the given value is an `Infinity`.
** `isNotInfinity(value: number): boolean`
— returns `true` if the given value is not an `Infinity`.


== Base (Radix)

The `parseFloat()`, `parseInt()`, and `Number.prototype.toString()` functions are combined
into polymorphic shortcuts for readability and avoiding `NaN`.

* `decimal(value: number): string`
— returns a string representing a specified number in decimal notation (base 10).
* `decimal(value: string): number | null`
— returns a `number` parsed from a given string in decimal notation (base 10).
If the string cannot be parsed, returns `null`.
+
* `binary(value: Integer): string`
— returns a string representing a specified integer in binary notation (base 2).
* `binary(value: string): Integer | null`
— Returns an integer `number` parsed from a given string in binary notation (base 2).
If the string cannot be parsed, returns `null`.
+
* `octal(value: Integer): string`
— returns a string representing a specified integer in octal notation (base 8).
* `octal(value: string): Integer | null`
— returns an integer `number` parsed from a given string in octal notation (base 8).
If the string cannot be parsed, returns `null`.
+
* `hexadecimal(value: Integer): string`
— returns a string representing a specified integer in hexadecimal notation (base 16).
* `hexadecimal(value: string): Integer | null`
— returns an integer `number` parsed from a given string in hexadecimal notation (base 16).
If the string cannot be parsed, returns `null`.

[NOTE]
====
When any of these functions is passed as a parameter to a generic function or method,
TypeScript does not recognize the polymorphic `(string): number` signature.
It requires to pass the `number` as a type parameter explicitly.

[source,typescript]
----
import { just } from '@perfective/common/maybe';
import { decimal } from '@perfective/common/number';

just('3.14').to(decimal) === just(3.14); // <.>
just(3.14).to<string>(decimal) === just('3.14'); // <.>
----
<1> The `(number): string` signature is recognized,
and `to()` method does not require a type parameter.
<2> The `(string): number` signature is not picked by the compiler
and `to()` method requires a type parameter to compile.
====


== Order

* Predicates:
** `isEqualTo(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is equal to a given `value`.
** `isNotEqualTo(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is not equal to a given `value`.
** `isGreaterThan(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is greater than a given `value`.
** `isGreaterThanOrEqualTo(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is greater than or equal to a given `value`.
** `isLessThan(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is less than a given `value`.
** `isLessThanOrEqualTo(value: number): Predicate<number>`
— creates a function that returns `true` if the input number is less than or equal to a given `value`.
+
* Sorting:
** `ascending(a: number, b: number): number`
— returns a negative number if the first argument is less than the second argument.
+
Can be used as a callback for the `Array.prototype.sort()` method to sort numbers in ascending order.
+
** `descending(a: number, b: number): number`
— Returns a positive number if the first argument is greater than the second argument.
+
Can be used as a callback for the `Array.prototype.sort()` method to sort numbers in descending order.


== Interval

* Type:
+
** `Interval` represents a https://en.wikipedia.org/wiki/Interval_(mathematics)[real interval] range.
+
* Constructors:
+
** `interval(min: number, max: number): Interval | null`
— creates an `Interval` from given `min` and `max` numbers.
If `min` is greater than `max`, returns `null`.
** `intervalFromPair(pair: readonly [number, number]): Interval | null`
— creates an `Interval` from a given pair of numbers, where the first number is `min` and the second is `max`.
If `min` is greater than `max`, returns `null`.
** `intervalFromValues(values: number[]): Interval | null`
— creates an `Interval` from the minimum and maximum numbers in a given array of numbers.
If the given array is empty, returns `null`.
** `intervalFromNullable(min: number | null, max: number | null): Interval | null`
— creates an `Interval` from the given `min` and `max` numbers, which can be null.
If the `min` is `null`, the interval will have a minimum of -∞.
If the `max` is `null`, the interval will have a maximum of +∞.
+
* Predicates:
+
** `isInInterval(interval: Interval): Predicate<number>`
— creates a predicate that checks returns `true`
if the input number is greater than or equal to the given `interval` minimum,
or is less than or equal the given `interval` maximum.
+
** `isInOpenInterval(interval: Interval): Predicate<number>`
— creates a predicate that checks returns `true`
if the input number is greater than the given `interval` minimum,
or is less than the given `interval` maximum.
+
** `isInLeftOpenInterval(interval: Interval): Predicate<number>`
— creates a predicate that checks returns `true`
if the input number is greater than the given `interval` minimum,
or is less than or equal the given `interval` maximum.
+
** `isInRightOpenInterval(interval: Interval): Predicate<number>`
— creates a predicate that checks returns `true`
if the input number is greater than or equal to the given `interval` minimum,
or is less than the given `interval` maximum.


== Bitmasks

* Types:
+
** `Flags<T extends number = number>`
— an `enum` object with a list of available bitmask flags.
** `Flag<T extends Flags>`
— a bitmask flag defined in a given `Flags` enum.
** `Bitmask<T extends Flags | number = number>`
— a bitmask consisting of one or more `Flags`.
+
* Constructor:
+
** `bitmask<T extends Flags | number = number>(flags: Bitmask<T>[]): Bitmask`
— creates a bitmask with all given flags raised.
+
* Predicates:
+
** `isFlagOn<T extends Flags | number>(bitmask: Bitmask<T>, flag: Bitmask<T>): boolean`
— returns `true` if a given flag is raised on a bitmask.
** `hasFlagOn<T extends Flags | number>(flag: Bitmask<T>): Unary<Bitmask<T>, boolean>`
— creates a function that returns `true` if a given `flag` is raised in the input bitmask.
+
* Functions:
+
** `raisedFlags<T extends number>(type: object, bitmask: Bitmask<T>): Member<T>[]`
— returns flags that are raised on the given bitmask.
