= Object

The `@perfective/common/object` package provides functions to work with the standard JS
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object[Object]` class.

* Types:
** `ObjectWithDefined<T, K extends keyof T>`
** `ObjectWithUndefined<T, K extends keyof T>`
** `ObjectWithNotNull<T, K extends keyof T>`
** `ObjectWithNull<T, K extends keyof T>`
** `ObjectWithPresent<T, K extends keyof T>`
** `ObjectWithAbsent<T, K extends keyof T>`
** `RecursivePartial<T>`
** `Entry<T = unknown>`
+
* Unit functions:
** `copy<T>(value: T): T`
— creates a shallow copy of the given value. (Experimental).
** `clone<T>(value: T): T`
— creates a clone (deep copy) of the given value. (Experimental).
** `pick<T, K extends keyof T>(record: T, ...property: readonly K[]): Pick<T, K>`
— creates a copy of the `record` only with the given `property`.
** `omit<T, K extends keyof T>(record: T, ...property: readonly K[]): Omit<T, K>`
— creates a copy of the `record` without the given `property`.
** `filter<T, K extends keyof T>(record: T, condition: Predicate<T[K]>): Partial<T>`
— creates a copy of the `record` where each value meets the `condition`.
** `assign<T, V = Partial<T>>(value: T, ...overrides: (V | Partial<T>)[]): T & V`
— creates a shallow copy of the given value with the given overrides.
** `recordFromArray(array: string[]): Record<string, number>`
** `recordFromEntries(entries: Entry[]): Record<string, unknown>`
** `recordWithPicked<T, K extends keyof T>(...property: readonly K[]): Unary<T, Pick<T, K>>`
— partially applies the `pick()` function for the given `property`.
** `recordWithOmitted<T, K extends keyof T>(...property: readonly K[]): Unary<T, Omit<T, K>>`
— partially applies the `omit()` function for the given `property`.
** `recordFiltered<T, K extends keyof T = keyof T>(condition: Predicate<T[K]>): Unary<T, Partial<T>>`
— partially applies the `filter()` function for the given `condition`.
+
* Type guards:
** `hasDefinedProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithDefined<T, K>`
** `hasUndefinedProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithUndefined<T, K>`
** `hasNotNullProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithNotNull<T, K>`
** `hasNullProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithNull<T, K>`
** `hasPresentProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithPresent<T, K>`
** `hasAbsentProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithAbsent<T, K>`
+
* Predicates:
** `isObject<T>(value: T | null): boolean`
** `isRecord<T>(value: T): boolean`
— returns `true` when the value is an object created from the `Object` class (not an `Array`, `Date`, etc.).
** `isTruthy<T>(value: T): boolean`
** `isFalsy<T>(value: T): boolean`
** `isEmpty<T>(value: T): boolean`
— returns `true` when the value is truthy or is a non-empty array or object.
** `hasMethod(value: unknown, method: string): boolean`
— returns `true` when a given value implements a given `method`.
** `hasNoMethod(value: unknown, method: string): boolean`
— returns `true` when a given value implements a given `method`.
+
* Reducers:
** `toRecordFromEntries(record: Record<string, unknown>, value: Entry): Record<string, unknown>`
+
* Property functions:
** `property<T, K extends keyof T>(property: K): Unary<T, T[K]>`
** `property<T, K extends keyof T>(property: K, condition: Predicate<T[K]>): Predicate<T>`
** `by<T, K extends keyof T>(property: K, ordering: Compare<T[K]>): Compare<T>`


== Input

One of the challenges in API development is declaring type of requests (inputs).
On the client side these types need to be as strict as possible
(e.g., all fields that are required must be marked as required).
On the server side the same type need to be treated as completely unknown, unvalidated data.
If the type is written for the client side, compiler will not be able to enforce any checks on the server side.
At the same time, server side cannot just use the plain `unknown` type,
as any access to properties will be prohibited (with strict compiler settings).

To resolve this issue, the `Input<T>` type is introduced.
It recursively adds `unknown`, `null`, and `undefined` to the type of every field or value.
That allows to enforce validation of input data,
while declaring the original type `T` can be declared in strict mode for the client side.

Validation functions and additional input types cover default https://www.json.org/json-en.html[JSON] types:
`object`, `array`, `string`, `number`, `boolean`, and `null`.

* Types:
** `Input<T>`
** `InputArray<T>`
** `InputObject<T>`
** `InputPrimitive<T>`
+
* Unit function:
** `input<T>(input: unknown): Input<T>`
— type cast to `Input<T>`.
+
* Basic validation functions:
** `stringInput(input: Input<string>): string | undefined`
** `numberInput(input: Input<number>): number | undefined`
** `booleanInput(input: Input<boolean>): boolean | undefined`
** `arrayInput<T>(input: Input<T[]>): Input<T>[] | undefined`
— checks that the `input` is an array and returns it as an array of _unvalidated_ elements.
** `objectInput<T>(input: Input<T>): InputObject<T> | undefined`
— checks that the `input` is a non-null, non-array object, and returns it as an object with _unvalidated_ properties.
** `nullInput(input: Input<null>): null | undefined`.

.Use `Maybe` chain to validate inputs
[source,typescript]
----
import { panic } from '@perfective/common/error';
import { maybe } from '@perfective/common/maybe';
import { isNatural, Natural } from '@perfective/common/number';
import { Input, InputObject, numberInput, objectInput } from '@perfective/common/object';

interface ExampleParams {
    id: number;
}

interface Example {
    params: ExampleParams;
}

function userId(request: Input<Example>): Natural {
    return maybe(request) // <.>
        .to<InputObject<Example>>(objectInput) // <.>
        .pick('params')
        .to<InputObject<ExampleParams>>(objectInput)
        .pick('id')
        .to(numberInput) // <.>
        .otherwise(panic('User ID is not defined'))
        .that(isNatural) // <.>
        .or(panic('User ID is invalid'));
}
----
<1> `request` may be `undefined`.
<2> At the moment type transformations are not inferred correctly,
so explicit type need to provided for `objectInput`.
<3> Last validation of the input structure.
<4> Final validation of the input, specific for the function.

[NOTE]
====
A custom validation monad may be added later to allow "collecting" all validation errors and warnings.
====


== Enum

* Types:
** `Enum<T extends number | string>` — a record generated based on the `enum` keyword;
** `Member<T extends number | string>` — key of an enum.
* Functions:
** `members<T extends number | string, E extends Enum<T>>(value: E): Member<T>[]`
— returns a list of `enum` keys.
