= Object

The `@perfective/object` package provides functions to work with the standard JS
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object[Object]` class.

* Types:
** `ObjectWithDefined<T, K extends keyof T>`
** `ObjectWithUndefined<T, K extends keyof T>`
** `ObjectWithNotNull<T, K extends keyof T>`
** `ObjectWithNull<T, K extends keyof T>`
** `ObjectWithPresent<T, K extends keyof T>`
** `ObjectWithAbsent<T, K extends keyof T>`
** `RecursivePartial<T>`
+
* Unit functions:
** `recordFromArray(array: string[]): Record<string, number>`
+
* Type guards:
** `hasDefinedProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithDefined<T, K>`
** `hasUndefinedProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithUndefined<T, K>`
** `hasNotNullProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithNotNull<T, K>`
** `hasNullProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithNull<T, K>`
** `hasPresentProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithPresent<T, K>`
** `hasAbsentProperty<T, K extends keyof T>(property: K, ...and: readonly K[]): (value: T) => value is ObjectWithAbsent<T, K>`
+
* Predicates:
** `isObject<T>(value: T | null): boolean`
** `isTruthy<T>(value: T): boolean`
+
* Property functions:
** `property<T, K extends keyof T>(property: K): Unary<T, T[K]>`
** `property<T, K extends keyof T>(property: K, condition: Predicate<T[K]>): Predicate<T>`
** `by<T, K extends keyof T>(property: K, ordering: Compare<T[K]>): Compare<T>`
