= Perfective Common for TypeScript

[IMPORTANT]
====
The code provided by this project relies on the strict http://typescriptlang.org[TypeScript] compiler checks.
Use of these packages in the regular JS projects may produce unexpected behavior and is undocumented.
For example,
a function that declares an argument as required relies on strict TSC `null` checks
and does not check value for `null` additionally.
====


== Installation

[source,bash]
----
npm install @perfective/common
----


== Features

While JavaScript supports the object-oriented paradigm,
the functional programming style allows writing more readable code in JS.
Hence, all provided data types (interfaces) are immutable,
and classes are used only to build fluent method chains
(considering methods as infix operators).

One of the base patterns used is to provide a unit (constructor) function named after each class
to discourage the use of the new operator
(for readability and consistency with the method chains).
Classes should only be used in function types declaration.
All non-abstract classes should be considered final even TypeScript does not allow to limit that.

This repo currently contains the following sub-packages:

* `link:https://github.com/perfective/ts.common/tree/main/src/array/index.adoc[@perfective/common/array]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array[Array]` class.
* `link:https://github.com/perfective/ts.common/tree/main/src/boolean/index.adoc[@perfective/common/boolean]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean[boolean]` values.
* `link:https://github.com/perfective/ts.common/tree/main/src/error/index.adoc[@perfective/common/error]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error[Error]`
and related classes.
* `link:https://github.com/perfective/ts.common/tree/main/src/function/index.adoc[@perfective/common/function]`
— functions and types for functional programming and logical operations.
* `link:https://github.com/perfective/ts.common/tree/main/src/match/index.adoc[@perfective/common/match]`
— functions to support a functional switch-case.
* `link:https://github.com/perfective/ts.common/tree/main/src/maybe/index.adoc[@perfective/common/maybe]`
— a `Maybe` monad (https://en.wikipedia.org/wiki/Option_type[Option type]) implementation.
* `link:https://github.com/perfective/ts.common/tree/main/src/number/index.adoc[@perfective/common/number]`
— functions and types to work with the real numbers.
* `link:https://github.com/perfective/ts.common/tree/main/src/object/index.adoc[@perfective/common/object]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object[Object]` class.
* `link:https://github.com/perfective/ts.common/tree/main/src/number/index.adoc[@perfective/common/promise]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` class.
* `link:https://github.com/perfective/ts.common/tree/main/src/result/index.adoc[@perfective/common/result]`
— a `Result` monad (https://en.wikipedia.org/wiki/Result_type[Result type]) implementation.
* `link:https://github.com/perfective/ts.common/tree/main/src/string/index.adoc[@perfective/common/string]`
— functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String[String]` class.

The package has a 100% unit test coverage.


== Roadmap

The primary development focus is to provide convenient functions
and detailed documentation in the existing packages.

=== Version 1.0

* Must target https://262.ecma-international.org/6.0/[ECMAScript 6].
* May support newer versions of ECMAScript if they have wide browser or TypeScript support.
* Legacy browsers support may be provided using `@babel`.


=== Packages

* `@perfective/common/date`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date[Date]` type.
+
* `@perfective/common/function`:
** Ensure coverage of the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function[Function]`,
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator[Generator]`,
and `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction[GeneratorFunction]` types.
** Consider support for
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction[AsyncFunction]` (ES 8)
+
* `@perfective/common/i18n`:
** Add support for localization functions.
+
* `@perfective/common/number`:
** Ensure coverage of:
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number[Number]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math[Math]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity[Infinity]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY[Number.NEGATIVE_INFINITY]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/POSITIVE_INFINITY[Number.POSITIVE_INFINITY]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite[Number.isFinite()]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite[isFinite()]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN[NaN]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN[isNaN()]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN[Number.isNaN()]`
+
* `@perfective/common/promise`:
** Ensure coverage of the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` type.
+
* `@perfective/common/reflect`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect[Reflect]` type.
+
* `@perfective/common/regexp`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp[RegExp]` type.
+
* `@perfective/common/symbol`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol[Symbol]` type.
+
* `@perfective/common/uri`:
** Ensure support of:
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI[encodeURI]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent[encodeURIComponent]`,
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI[decodeURI]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent[decodeURIComponent]`,
and `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError[URIError]`.
** Consider custom support for:
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape[escape]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape[unescape]`.
+
* `@perfective/common/url`
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/API/URL[URL]` WebAPI.


=== References

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference[MDN JavaScript Reference]
* https://en.wikipedia.org/wiki/ECMAScript[ECMAScript Wikipedia]
* https://262.ecma-international.org/6.0/[ECMA Script 2015 Specification]


== Terminology

* _Unit function_ — a function that creates a new object or a function.
Term used as distinguished from `constructor` and `new` keywords.


=== Common patterns

* For each declared `interface` or `class`,
there is at least one unit function to instantiate it.
This function has the same name as the interface/class but in camelCase.
+
* For each declared class,
there are two https://www.typescriptlang.org/docs/handbook/2/narrowing.html[type guards] to check
if a given value is an instance of that class or not.
These functions have prefixes `is` and `isNot`.
+
* Declared interfaces and types may have other predicates
with the `is`/`isNot` prefixes.


=== TypeScript configuration

The project contains a group of TSConfig files to maintain a productive development environment
with the WebStorm IDE:

* The base file with the TypeScript compiler configuration is `tsconfig.strict.json`.
It contains all the default (strict) compiler settings.
* The root `tsconfig.json` is picked up by WebStorm and is used by Jest.
* `tsconfig.build.json` contains the defaults for the build,
and is further overridden in `gulpfile.js` for CommonJS, ESM, and declaration files compilation.


=== Documentation

This project uses the https://asciidoctor.org[AsciiDoc] format for its documentation.
Each sub-package has an `index.adoc` file that is included into the package `src/index.adoc`.
It is automatically compiled into the `dist/docs.html` file
and is published with all other package files.

[NOTE]
====
Unfortunately, https://www.npmjs.com[npmjs] only supports Markdown.
As a result, in addition to this `README.adoc` for the repository,
there is a `README.md` file with only basic information for the
https://www.npmjs.com/package/@perfective/common[npm page].
====
