= Perfective Common for TypeScript


== Installation

[source,bash]
----
npm install @perfective/common
----


== Key Features

The `@perfective/common` package facilitates writing highly readable functional code.
It focuses on providing functions to handle ECMAScript types
and to easily compose functions together.


=== Maybe monad

The `link:https://github.com/perfective/ts.common/tree/main/src/maybe/index.adoc[@perfective/common/maybe]` package
provides a Maybe monad implementation.

It allows you to write and compose functions that accept only present (defined and non-null) values
It helps to avoid additional complexity and noise of handling `null` and `undefined` values.

For example, consider you have the `User` and `Name` types below,
and you want to output a user's full name.

[source,typescript]
----
interface User {
    name?: Name;
}

interface Name {
    first: string;
    last: string;
}
----

If you write functions that have to handle `null` and `undefined` values,
then you would have to write something like:

[source,typescript]
----
import { isPresent } from '@perfective/common';
import { isNotEmpty } from '@perfective/common/string';

function userNameOutput(user: User | null | undefined): string {
    if (isPresent(user)) {
        const name = fullName(user.name);
        if (isPresent(name)) {
            return name;
        }
    }
    throw new Error('User name is unknown');
}

function fullName(name: Name | null | undefined): string | null {
    if (isPresent(name)) {
        const name = `${name.first} ${name.last}`.trim();
        if (isNotEmpty(name)) {
            return name;
        }
    }
    return null;
}
----

When using the `link:https://github.com/perfective/ts.common/tree/main/src/maybe/index.adoc[Maybe]` monad you can write
simpler and more readable functions:

[source,typescript]
----
import { panic } from '@perfective/common/error';
import { just, maybe } from '@perfective/common/maybe';
import { isNotEmpty, trim } from '@perfective/common/string';

function userNameOutput(user: User | null | undefined): string {
    return maybe(user)
        .pick('name') // <.>
        .onto(fullName) // <.>
        .or(panic('User name is unknown')); // <.>
}

function fullName(name: Name): Maybe<string> {
    return just(`${name.first} ${name.last}`)
        .to(trim) // <.>
        .that(isNotEmpty); // <.>
}
----
<.> `link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybepick[Maybe.pick()]`
provides a strictly-typed "optional chaining" of the `Maybe.value` properties.
<.> `link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybeonto[Maybe.onto()]`
(flat) maps a `Maybe.value` to another `Maybe`.
<.> `https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybeor[Maybe.or()]`
extracts a `value` from the `Maybe` with a given fallback.
(or allows to throw an error).
<.> `link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybethat[Maybe.that()]`
filters a value inside `Maybe`.
<.> `link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybeto[Maybe.to()]` maps a value inside `Maybe` using a given callback.

In addition to these methods,
the `link:https://github.com/perfective/ts.common/tree/main/src/maybe/index.adoc[Maybe]` type also provides:
`link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybeinto[Maybe.into()]`,
`link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybewhich[Maybe.which()]`,
`link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybewhen[Maybe.when()]`,
`link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybeotherwise[Maybe.otherwise()]`,
and `link:https://github.com/perfective/ts.common/blob/main/src/maybe/index.adoc#maybethrough[Maybe.through()]` methods.


== Result monad

The `@perfective/common/result` package provides a Result monad
(a concrete case of an Either monad).
It allows you to treat errors as part of function result
and chain processing of such results.

For example,
consider you are writing a function that loads a backend entity based on the user input.

.Example of the provided functions and types.
[source,typescript]
----
interface Request {
    entity: string;
    id: number;
}

interface User {
    id: number;
    username: string;
}

/**
 * @throws {Error} If a given input is empty or is not a number.
 */
declare function numberInput(input: string): number;

declare function request(entity: string): (id: number) => Request;

declare function user(request: Request): User;
----

Writing an imperative code you would have:

[source,typescript]
----
function userOutput(input: string): User {
    let id: number;
    try {
        id = numberInput(input);
    } catch (error: Error) {
        id = 0;
    }
    const userRequest = request('user');
    return user(userRequest(id));
}
----

Using the `Result` your code would be:

[source,typescript]
----
import { recovery, Result, resultOf } from '@perfective/common/result';

function userOutput(id: string): Result<User> {
    return resultOf(() => numberInput(id))
        .into(recovery(0))
        .to(request('user'))
        .to(user);
}
----

The `Result` link:https://github.com/perfective/ts.common/blob/main/src/result/index.adoc#using-result-with-promise[integrates]
with the `Promise` using the `promisedResult()` and `settledResult()` functions.


== Packages

Packages are organized and named around their primary type:

* `link:https://github.com/perfective/ts.common/blob/main/src/value/index.adoc[@perfective/common]`
— functions and types to handle types (e.g., `TypeGuard` interface), `null`, `undefined`, and `void` values.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/array/index.adoc[@perfective/common/array]`
— functions and types to handle
link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array[arrays].
+
* `link:https://github.com/perfective/ts.common/tree/main/src/boolean/index.adoc[@perfective/common/boolean]`
— functions and types to handle
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean[boolean]` values.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/error/index.adoc[@perfective/common/error]`
— functions and types to handle
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error[Error]`
and related classes.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/function/index.adoc[@perfective/common/function]`
— functions and types for functional programming.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/match/index.adoc[@perfective/common/match]`
— functions and types for a functional style `switch-case`.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/maybe/index.adoc[@perfective/common/maybe]`
— a `Maybe` monad (https://en.wikipedia.org/wiki/Option_type[Option type]) implementation.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/number/index.adoc[@perfective/common/number]`
— functions and types to handle
link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number[numbers].
+
* `link:https://github.com/perfective/ts.common/tree/main/src/object/index.adoc[@perfective/common/object]`
— functions and types to handle the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object[Object]` class.
* `link:https://github.com/perfective/ts.common/tree/main/src/number/index.adoc[@perfective/common/promise]`
— functions and types to handle the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` class.
+
* `link:https://github.com/perfective/ts.common/tree/main/src/result/index.adoc[@perfective/common/result]`
— a `Result` monad (https://en.wikipedia.org/wiki/Result_type[Result type]) implementation.
* `link:https://github.com/perfective/ts.common/tree/main/src/string/index.adoc[@perfective/common/string]`
— functions and types to handle
link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String[strings].

The packages have full unit tests coverage.

[IMPORTANT]
====
The code provided by this project relies on the strict https://www.typescriptlang.org[TypeScript] compiler checks.
Use of these packages in the regular JS projects may produce unexpected behavior and is undocumented.
For example,
a function that declares an argument as _required_ relies on strict TSC `null` checks
and does not check value for `null` additionally.
====


== Roadmap

The primary development focus is to provide convenient functions
and detailed documentation in the existing packages.

=== Version 1.0

* Must target https://262.ecma-international.org/6.0/[ECMAScript 6].
* May support newer versions of ECMAScript if they have wide browser or TypeScript support.
* Legacy browsers support may be provided using `@babel`.


=== Packages

* `@perfective/common/date`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date[Date]` type.
+
* `@perfective/common/function`:
** Ensure coverage of the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function[Function]`,
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator[Generator]`,
and `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction[GeneratorFunction]` types.
** Consider support for
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction[AsyncFunction]` (ES 8)
+
* `@perfective/common/i18n`:
** Add support for localization functions.
+
* `@perfective/common/number`:
** Ensure coverage of:
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number[Number]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math[Math]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity[Infinity]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/NEGATIVE_INFINITY[Number.NEGATIVE_INFINITY]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/POSITIVE_INFINITY[Number.POSITIVE_INFINITY]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite[Number.isFinite()]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isFinite[isFinite()]`
*** `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN[NaN]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN[isNaN()]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN[Number.isNaN()]`
+
* `@perfective/common/promise`:
** Ensure coverage of the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` type.
+
* `@perfective/common/reflect`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect[Reflect]` type.
+
* `@perfective/common/regexp`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp[RegExp]` type.
+
* `@perfective/common/symbol`:
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol[Symbol]` type.
+
* `@perfective/common/uri`:
** Ensure support of:
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI[encodeURI]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent[encodeURIComponent]`,
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI[decodeURI]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent[decodeURIComponent]`,
and `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError[URIError]`.
** Consider custom support for:
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape[escape]`
/ `link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/unescape[unescape]`.
+
* `@perfective/common/url`
** Add support for the
`link:https://developer.mozilla.org/en-US/docs/Web/API/URL[URL]` WebAPI.


=== References

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference[MDN JavaScript Reference]
* https://en.wikipedia.org/wiki/ECMAScript[ECMAScript Wikipedia]
* https://262.ecma-international.org/6.0/[ECMA Script 2015 Specification]


== Common patterns

* While JavaScript supports the object-oriented paradigm,
the functional programming style allows writing more readable code in JS.
Hence, all provided data types (interfaces) are immutable,
and classes are used only to build fluent method chains
(considering methods as infix operators).
+
* One of the base patterns used is to provide a constructor function named after each class
to discourage the use of the `new` operator
(for readability and consistency with the method chains).
Classes should only be used in types declaration.
All non-abstract classes should be considered final even TypeScript does not provide a `final` keyword.
+
* For each declared `interface` or `class`,
there is at least one unit function to instantiate it.
This function has the same name as the interface/class but in camelCase.
+
* For each declared class,
there are two https://www.typescriptlang.org/docs/handbook/2/narrowing.html[type guards] to check
if a given value is an instance of that class or not.
These functions have prefixes `is` and `isNot`.
+
* Declared interfaces and types may have other predicates
with the `is`/`isNot` prefixes.


== TypeScript configuration

The project contains a group of TSConfig files to maintain a productive development environment
with the WebStorm IDE:

* The base file with the TypeScript compiler configuration is `tsconfig.strict.json`.
It contains all the default (strict) compiler settings.
* The root `tsconfig.json` is picked up by WebStorm and is used by Jest.
* `tsconfig.build.json` contains the defaults for the build,
and is further overridden in `gulpfile.js` for CommonJS, ESM, and declaration files compilation.


== Documentation

This project uses the https://asciidoctor.org[AsciiDoc] format for its documentation.
Each sub-package has an `index.adoc` file that is included into the package `src/index.adoc`.
It is automatically compiled into the `dist/docs.html` file
and is published with all other package files.

[NOTE]
====
Unfortunately, https://www.npmjs.com[npmjs] only supports Markdown.
As a result, in addition to this `README.adoc` for the repository,
there is a `README.md` file with only basic information for the
https://www.npmjs.com/package/@perfective/common[npm page].
====
