= Function
:mdn-js-globals: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

The `@perfective/common/function` package provides types and functions for the functional programming style.
As functions with more than three arguments are considered a code smell,
this package only declares the `Nullary`, `Unary`, `Binary`, and `Ternary` types.
The functions of higher arity is unlikely to be added to the package.

== Type Guards

** `isFunction<T>(value: Function | T): value is Function`
** `isNotFunction<T>(value: Function | T): value is T`


== Nullary functions

* `Nullary<T>`
— a function without arguments:
** `isNullary<F extends Function>(f: F): boolean`
— returns `true` when function accepts no arguments
(does not count a variadic argument).
** `constant<T>(value: T): Nullary<T>`
— creates a function that returns that same value.
+
* `Void`
— a procedure without arguments:
** `naught(): void`
— an empty function to be passed as a callback when a no-op behavior is required.
+
* `Value<T> = T | Nullary<T>`
— represent a value, or a function that returns a value
(e.g. for lazy evaluation).
** `valueOf<T>(value: Value<T>): T`
— evaluates the given value.


== Unary functions

* `Unary<X, V>`
— a function with one argument:
** `isUnary<F extends Function>(f: F): boolean`
— returns `true` when function accepts only one argument
(does not count a variadic argument).
** `same<T>(value: T): T`
— returns a given value.
+
* `UnaryVoid<T> = (value: T) => void`
— a procedure with one argument.


== Binary functions

* `Binary<X, Y, V>`
— a function with two arguments (`X` and `Y`).
** `isBinary<F extends Function>(f: F): boolean`
— returns `true` when function accepts exactly two arguments
(does not count a variadic argument).


== Ternary functions

* `Ternary<X, Y, Z, V>`
— a function with three arguments (`X`, `Y`, and `Z`).
** `isTernary<F extends Function>(f: F): boolean`
— returns `true` when function accepts exactly three arguments
(does not count a variadic argument).


== Length

`Length` type defines a kind of objects that have "length" (arrays, strings, etc).

[source,typescript]
----
interface Length {
    length: number;
}
----

* Functions
+
** `length<L extends Length>(value: L): number`
— returns value of the `length` property of a given `value`.
+
* Predicates
+
** `hasLength<L extends Length>(length: number): Predicate<L>`
— returns a `Predicate` that checks if a value has a given `length`.
+
** `isNotEmpty<L extends Length>(value: L): boolean`
— returns `true` if a given `value` has non-positive length.
+
** `isEmpty<L extends Length>(value: L): boolean`
— returns `true` if a given `value` has `length` greater than 0.
+
* Reducers
+
These functions can be used as a callback for `Array.prototype.reduce`.
+
** `toShortest<T extends Length>(shortest: T, value: T): T`
— returns the shortest of two given values.
+
** `toLongest<T extends Length>(longest: T, array: T): T`
— returns the longest of two given values.


== Arguments

* `BiMap<T1, U1, T2, U2> = [Unary<T1, U1>, Unary<T2, U2>]`
— a pair of callbacks to map both arguments of a given function at the same time.
+
* `BiFold<T1, T2, U> = [Unary<T1, U>, Unary<T2, U>]`
— a pair of unary callbacks to map both arguments `T1` and `T2` of a function into the same type `U`.


== Roadmap

* Provide functions for the standard
`link:{mdn-js-globals}/Function[Function]` object.
* Add currying and partial application support.
