= Maybe monad

`@perfective/common/maybe` package provides an https://en.wikipedia.org/wiki/Option_type[Option type] implementation.
It is inspired by the Haskell
`link:https://en.wikibooks.org/wiki/Haskell/Understanding_monads/Maybe[Maybe]` monad
and satisfies the https://en.wikipedia.org/wiki/Monad_(functional_programming)#Analysis[monad laws].

`Maybe` type simplifies handling of the absent (`null`/`undefined`) values
and provides methods that are called only when the value is present.
It allows the creation of chained calls similar to `Promise.then()` and RxJS `pipe()`.


== Handling `null` and `undefined` values

In JavaScript, two types represent an "absence" of value: `undefined` and `null`.
So the dichotomies like `Just | Nothing` or `Some | None` do not fit precisely
and require additional logic to cover all the cases: `T | null | undefined`.
For example, when you create a new `Maybe<T>` with a `null` value,
it has to maintain the value as `null` and should not change it to `undefined`.

.`Maybe<T>` maintains the original value.
[source,typescript]
----
import { maybe, nil, nothing } from '@perfective/common/maybe';
import { isGreaterThan } from '@perfective/common/number';

maybe(3.14).value === 3.14;

maybe(undefined).value === undefined;
nothing().value === undefined; // <.>
maybe(3.14)
    .that(isGreaterThan(4))
    .value === undefined; // <.>

maybe(null).value === null;
nil().value === null; // <.>
maybe(null)
    .that(isGreaterThan(4))
    .value === null; // <.>
----
<.> The `nothing()` function is the default unit function for `Nothing<T>`
and returns a memoized `new Nothing(undefined)`.
<.> By default, `Maybe` uses `undefined` for the absent value.
<.> The `nil()` function is the secondary unit function for `Nothing<T>`
and returns a memoized `new Nothing(null)`.
<.> If the original value is `null`,
`null` will be returned as an absent value after all transformations.

It is not always desired to have both `undefined` and `null` excluded.
For example, consider you have a field in an API that is `null` when there is no data,
but the field is not returned if a user does not have access to it.
In this case, you may prefer to fall back from `null` to a default value
but to throw an error for `undefined`.

To cover these cases, `@perfective/common/maybe` provides the `Maybe.into()` method:
it allows to apply a function that handles either `T`, `null`, or `undefined` value.

.The original absent value (`null` or `undefined`) is maintained through transformations.
[source,typescript]
----
import { isNull, isUndefined } from '@perfective/common';
import { panic } from '@perfective/common/error';
import { just } from '@perfective/common/maybe';

interface ApiResponse {
    username?: string | null;
}

function username(response: ApiResponse) {
    return just(response)
        .pick('username')
        .into((username: string | null | undefined) => { // <.>
            if (isUndefined(username)) {
                return panic('Unknown username');
            }
            if (isNull(username)) {
                return 'anonymous';
            }
            return username;
        });
}
----
<.> As  `Maybe` preserves the original type,
the result of the `pick()` can be either `nothing()` or `nil()`.
So `Maybe.into()` will have a correct value on input.


== Preserving the monad type

This package strictly preserves the type of the monad.
For example,
if you have a `Just` type and apply a function that returns a present value,
then the result will also be of type `Just`.

.Difference between `Maybe`, `Just` and `Nothing` contexts.
[source,typescript]
----
function maybeDecimal(value: number | null | undefined): Maybe<string> {
    return maybe(value).to(v => v.toString(10)); // <.>
}

function justDecimal(value: number): Just<string> {
    return maybe(value).to(v => v.toString(10)); // <.>
}

function nothingDecimal(value: null | undefined): Nothing<string> {
    return maybe<number>(value).to(a => a.toString(10)); // <.>
}
----
<.> The argument of the `maybeDecimal` function is `number | null | undefined`.
So the `maybe()` function returns `Maybe<number>`
(which is either `Just<number>` or `Nothing<number>`).
The result of the function may also be `Just` or `Nothing`,
because we can not be sure that the `to()` method will be called,
even the `v => v.toString(10)` returns a `string` for any `number` input.
+
<.> The argument of the `justDecimal` is always a `number`.
The `maybe()` function returns `Just<number>`,
because the value is _always_ present.
`maybe` has a custom overload signature,
and compiler also knows,
that `maybe` returns `Just<number>`.
+
As the `v => v.toString(10)` result is always a `string`,
compiler also knows that the result of the whole chain remains present.
And the return type can be set as `Just<string>`.
+
<.> Similarly, when the value can only be `null` or `undefined`,
the `maybe()` function returns `Nothing<number>` in compile time and in runtime.
And the return type of the whole chain can be set to `Nothing<string>`.


== Using `onto()` and `to()` methods

Both `Maybe.onto()` and `Maybe.to()` methods  apply a given function
only when the value is present.
But `onto` requires the function to return the next `Maybe` instance,
while `to` will wrap the returned value into `Maybe`.

When writing functions that use Maybe chaining,
the best practice is to return the packed value (as `Maybe`, `Just`, or `Nothing`).
This allows a consumer of the function to decide how they want to unpack it
or to keep it as `Maybe` for the next chain.

When you have a function of non-Maybe types,
then you have to use `Maybe.to`.

.For example, consider you are writing a function to parse a date.
[source,typescript]
----
function isValidDate(date: Date): boolean {
    return date.toString() !== 'Invalid Date'; <.>
}

function parsedDate(input: string): Maybe<Date> { <.>
    const date = new Date(input);
    if (isValidDate(date)) {
        return just(date);
    }
    return nothing();
}

interface BlogPost {
    createdAt: string;
}

function dbDate(input: BlogPost): Date { <.>
    return just(input)
        .pick('createdAt')
        .onto(parsedDate)
        .or(panic('Invalid "Created At" Date'));
}

function jsonDate(input: BlogPost): string|null { <.>
    return just(input)
        .pick('createAt')
        .onto(parsedDate)
        .or(null);
}

function formattedCreatedAt(input: BlogPost): string { <.>
    return just(input)
        .pick('createdAt')
        .onto(parsedDate)
        .or('Unknown date');
}
----
<.> The `new Date()` constructor creates a `Date` object even for
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#return_value[invalid inputs].
<.> We postpone the decision of how to handle an invalid value.
By returning `Maybe<Date>` (instead of `Date|null` or throwing an error)
we allow consumers of the function to make a decision that is most appropriate to their situation.
<.> When we record value to the database,
it has to be valid.
So we must throw an error when the date is invalid.
<.> When we return an API response,
a `null` for invalid dates is ok.
<.> When we try to format a date in the UI,
we may prefer a readable fallback.


== Using the `into()` method with the `maybeFrom()` function

The `Maybe.into()` method allows reducing a Maybe instance into a different type.
It applies the argument function for present and absent values.
In combination with the `maybeFrom()` function,
it allows to apply functions with custom handling of absent values
and return a new `Maybe` instance.

[source,typescript]
----
import { isAbsent } from '@perfective/common';
import { just, maybe, maybeFrom } from '@perfective/common/maybe';

function decimal(value: number | null | undefined): string {
    if (isAbsent(value)) {
        return '0'; // <.>
    }
    return value.toString(10);
}

maybe(null).onto(x => maybe(decimal(x))) != just(decimal(null)); // <.>
maybe(null).to(decimal) != just(decimal(null)); // <.>

maybe(null).into(x => maybe(decimal(x)) == just(decimal(null)) // <.>
maybe(null).into(maybeFrom(decimal)) == just(decimal(null)) // <.>
----
<.> The `decimal()` function returns a default value for the absent values
instead of returning another absent value
(or throwing an error).
<.> As a result, when `decimal()` is applied through the `Maybe.onto()` method,
it breaks the left-identity monad law.
<.> Applying `decimal()` through `Maybe.to()` gives the same incorrect result.
<.> Using the `Maybe.into()` method allows working around this issue
because `Maybe.into()` is called for all Maybe values
(not only present values).
<.> Use the `maybeFrom()` function as a shortcut.

[NOTE]
====
Since v0.9.0,
`Maybe.into(maybeFrom)` replaced the `Maybe.lift(map)` method.
====


== Reference

=== Types

* `Maybe<T>`
— an abstract class, represents either `Just<T>` or `Nothing<T>`.
* `Just<T>`
— represents a defined non-null value of type `T`.
* `Nothing<T>`
— represents an `undefined` or `null` value.


=== Functions

* `maybe<T>(value: T | null | undefined): Maybe<T>`
— creates an instance of `Just` when the `value` is present,
or returns a memoized instance of `Nothing`
with either `null` or `undefined` `value`.
* `maybeFrom<T, U>(map: Unary<T | null | undefined, U | null | undefined>): Unary<T | null | undefined, Maybe<U>>`
* `just<T>(value: Present<T>): Just<T>`
— creates an instance of `Just` with a given defined non-null `value`.
A _unit_ (_return_) function for the `Maybe` monad.
* `justFrom<T, U>(map: Unary<T | null | undefined, Present<U>>): Unary<T | null | undefined, Just<U>>`
— creates a function that applies a given `map` to a value
and returns the result wrapped into a `Just`.
* `nothing<T>(): Nothing<T>`
— returns a memoized instance of `Nothing` with an `undefined` value.
* `nil<T>(): Nothing<T>`
— returns a memoized instance of `Nothing` with a `null` value.


=== Type Guards

* `isMaybe<T, U>(value: Maybe<T> | U): value is Maybe<T>`
— returns `true` if a given value is a `Maybe`.
** `isNotMaybe<T, U>(value: Maybe<T> | U): value is U`
— returns `true` if a given value is not a `Maybe`.
+
* `isJust<T, U>(value: Just<T> | U): value is Just<T>`
— returns `true` if a given value is a `Just`.
** `isNotJust<T, U>(value: Just<T> | U): value is U`
— returns `true` if a given value is not a `Just`.
+
* `isNothing<T, U>(value: Nothing<T> | U): value is Nothing<T>`
— returns `true` if a given value is a `Nothing`
+ `isNotNothing<T, U>(value: Nothing<T> | U): value is U`
— returns `true` if a given value is not a `Nothing`.


=== `Maybe.onto()`

* `Maybe.onto<U>(flatMap: (value: T) => Maybe<Present<U>>): Maybe<Present<U>>`
** for a `Just`, applies a given `flatMap` callback to the `Just.value` and returns the result;
** for a `Nothing`, ignore the `flatMap` callback and returns the same `Nothing`.

[INFO]
====
This method is similar to the `mergeMap`/`switchMap` operator in `rxjs`
and the `flatMap` method in `java.util.Optional`.
====


=== `Maybe.to()`

* `Maybe.to<U>(map: (value: T) => U | null | undefined): Maybe<U>`
** for a `Just`, applies a given `map` callback to the `Just.value` and returns the result wrapped into a `Maybe`.
** for a `Nothing`, ignores the `map` callback and returns the same `Nothing`.

.Using `Maybe.to()` chaining
[source,typescript]
----
import { Maybe, maybe } from '@perfective/common/maybe';
import { lowercase } from '@perfective/common/string';

interface Name {
    first: string;
    last: string;
}

interface User {
    name?: Name;
}

function nameOutput(name: Name): string { // <.>
    return `${name.first} ${name.last}`;
}

function usernameOutput(user?: User): Maybe<string> {
    return maybe(user)
        .pick('name')
        .to(nameOutput)
        .to(lowercase);
}
----
<.> The `to` method wraps the result into `maybe`.

[INFO]
====
This method is similar to the `map` operator in `rxjs`
and the `map` method in `java.util.Optional`.
====


=== `Maybe.into()`

* `Maybe.into<U>(reduce: (value: T | null | undefined) => U): U`
— applies a given `reduce` callback to the `Maybe.value` and returns the result.
The purpose of `Maybe.into()` is to terminate the `Maybe`
and switch to a different type.

[NOTE]
====
Unlike `Maybe.onto()` and `Maybe.to()`,
the `Maybe.into()` method is called even if the `Maybe.value` is absent.

Unlike `Maybe.or()` and `Maybe.otherwise()`,
the `Maybe.into()` method is called even if the `Maybe.value` is present.
====

.Using `Maybe.into()`
[source,typescript]
----
import { Maybe, maybe } from '@perfective/common/maybe';
import { isPresent } from '@perfective/common';

function usernameRequest(userId: number | null | undefined): Promise<string> {
    if (isPresent(userId)) {
        return Promise.resolve({ userId });
    }
    return Promise.reject("UserId is missing");
}

function username(userId: Maybe<number>): Promise<string> {
    return userId.into(usernameRequest) // === usernameRequest(userId.value)
        .then(response => response.username) // <.>
        .catch(() => "Unknown");
}
----
<.> While passing the `Maybe.value` directly into the function is possible,
the `Maybe.into()` method allows to switch the chain to a different monadic type
and continue the chain with that new type.


=== `Maybe.pick()`

* `Maybe.pick<K extends keyof T>(property: Value<K>): Maybe<Present<T[K]>>`
** for a `Just`, returns the value of a given `property` of `Just.value` wrapped into a `Maybe`;
** for a `Nothing`, ignores the `property` and returns the same `Nothing`.

[NOTE]
====
Only properties that are defined on the value type are allowed.
====

It is similar to the
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#optional-chaining[optional chaining]
introduced in TypeScript 3.7
but does not generate excessive JS code for each `null` and `undefined` check in the chain.

.Using `Maybe.pick()` for optional chaining
[source,typescript]
----
import { panic } from '@perfective/common/error';
import { maybe } from '@perfective/common/maybe';

interface Name {
    first?: string;
    last?: string;
}

interface User {
    id: number;
    name?: Name;
}

function firstName(user?: User): string {
    return maybe(user).pick('name').pick('first').or(panic('Unknown first name')); // <.>
}

function userId(user: User): number {
    return just(user).pick('id').value; // <.>
}
----
<.> `maybe(user).pick('email')` will not compile,
as, in this example, the `User` type does not have an `email` property.
<.> When the value is `Just<T>`, and you `pick` a required property,
the result is `Just<U>` (where `U` is the type of that property).
Hence, starting a `maybe`-chain with `Just` is strongly recommended
if the value is already present.

[INFO]
====
This method is similar to the `pluck` operator in `rxjs`.
====


=== `Maybe.that()`

* `Maybe.that(filter: Predicate<T>): Maybe<T>`
** for a `Just`, if the value matches a given `filter` predicate,
returns the same `Just`, otherwise returns `Nothing`.
** for a `Nothing`, ignores the `filter` and returns itself.

.Using `Maybe.that()` to filter out a value
[source,typescript]
----
import { isNot } from '@perfective/common/function';
import { Maybe, just } from '@perfective/common/maybe';

function quotient(dividend: number, divisor: number): Maybe<number> {
    return just(divisor)
        .that(isNot(0)) // <.>
        .to(divisor => dividend / divisor);
}
----
<.> Returns `Nothing`, so `to()` will not be running its function.

[INFO]
====
This method is similar to the `filter` operator in `rxjs`
and the `filter` method in `java.util.Optional`.
====


=== `Maybe.which()`

* `Maybe.which<U extends T>(filter: TypeGuard<T, U>): Maybe<U>`
** for a `Just`, if the value matches a given `filter`
link:https://www.typescriptlang.org/docs/handbook/2/narrowing.html[_type guard_],
returns the same `Just` with a narrowed-down (differentiated) type.
** for a `Nothing`, ignores the `filter` and returns itself.


`Maybe.which()` is a filter method that requires passing a

It narrows down the result type based on the type guard.

.Using `Maybe.which()` to filter out values with absent properties.
[source,typescript]
----
import { Maybe, just } from '@perfective/common/maybe';
import { hasDefinedProperty } from '@perfective/common/object';

interface Name {
    first: string;
    last: string;
}

interface Username {
    first?: string;
    middle?: string;
    last?: string;
}

function nameOutput(name: Name): string {
    return `${name.first} ${name.last}`;
}

function usernameOutput(user: User): Maybe<string> {
    return just(user)
        .which(hasDefinedProperty('first', 'last')) // <.>
        .to(nameOutput); // <.>
}
----
<.> A broader `hasPresentProperty('first', 'last')` can also be used.
to guarantee that these properties' values are not `null` too.
But it is not required by the TS compiler `strictNullCheck`,
as these properties are _optional_, not _nullable_.
<.> `Name` type requires both `first` and `last` properties to be defined and not null,
so  without the `which` filter (with TS `strictNullChecks` enabled),
this code will not compile.


=== `Maybe.when()`

* `Maybe.when(condition: Proposition): Maybe<T>`
** for a `Just`, if a given `condition` is `true`, returns the same `Just`,
otherwise returns `Nothing`.
** for a `Nothing`, ignores the `condition` and returns itself.

[NOTE]
====
`Maybe.when()` should be used for better readability
instead of passing a nullary function into the `Maybe.that()`.
====

.Using `Maybe.when()` to filter out values based on a global condition.
[source,typescript]
----
import { just } from '@perfective/common/maybe';

function tokenLogOutput(token: string, isLog: boolean): Maybe<string> {
    return just(token)
        .when(isLog) // <.>
        .to(token => '***');
}
----
<.> You can use `when(() => isLog)`
if you only want to run the computation when the value is present.


=== `Maybe.otherwise()`

* `Maybe.otherwise(fallback: Value<T | null | undefined>): Maybe<T>`
** for a `Just`, ignores a given `fallback` value and returns itself.
** for a `Nothing`, returns a given `fallback` wrapped into a `Maybe`.

`Maybe.otherwise(fallback)` method allows passing a fallback value or throwing an error
if the value is _absent_.

.Using `Maybe.otherwise()` to continue the chain after the fallback.
[source,typescript]
----
import { panic } from '@perfective/common/error';
import { isNot } from '@perfective/common/function';
import { maybe } from '@perfective/common/maybe';

function range(min?: number, max?: number): number {
    return maybe(min)
        .otherwise(max) // <.>
        .that(isNot(0))
        .otherwise(panic('Invalid range'));
}
----
<.> `otherwise` wraps the fallback value into the next `Maybe`.


=== `Maybe.or()`

* `Maybe.or(fallback: Value<T | null | undefined>): T | null | undefined`
** for a `Just`, ignores a given `fallback` value and returns the `Just.value`.
** for a `Nothing`, returns the given `fallback` value.

The `Maybe.or(fallback)` method allows getting the present monad value
and providing a fallback value or throwing an error
when the value is missing.

.Using `Maybe.or()`
[source,typescript]
----
import { panic } from '@perfective/common/error';
import { maybe } from '@perfective/common/maybe';

interface Name {
    first: string;
    last: string;
}

interface User {
    name?: Name;
}

function nameOutput(name?: Name): string {
    return maybe(name)
        .to(name => `${name.first} ${name.last}`)
        .or('Unknown name'); // <.>
}

function userOutput(user?: User): string {
    return maybe(user)
        .pick('name')
        .to(nameOutput)
        .or(panic('Undefined user')); // <.>
}
----
<.> The fallback value type can be present or absent.
It allows returning only `undefined` or `null` if the value is absent.
<.> Using `panic` or any other function that throws an error when called
allows guaranteeing a present value is returned.

[INFO]
====
This method is similar to the `orElse`, `orElseGet`, and `orElseThrow` methods in `java.util.Optional`.
====


=== `Maybe.through()`

* `Maybe.through(procedure: (value: T) => void): Maybe<T>`
** for a `Just`, runs a given `procedure` with the `Just.value` as an argument, the returns the original `Just`.
** for a `Nothing`, ignores the `procedure` and returns itself.

[WARNING]
====
The `Maybe.through()` does not check if the given procedure mutates the present value.
====

[source,typescript]
----
import { maybe } from '@perfective/common/maybe';

function logError(error?: Error): Error|undefined {
    return maybe(error)
        .through(console.error);
}
----

[NOTE]
====
This method is similar to the `tap` operator in `rxjs`
and `ifPresent` method in `java.util.Optional`.
====


=== Lifting functions

Each method has a corresponding lifting function to be used in the `Array.prototype.map`
(or any other mapping method or operator).

[source,typescript]
----
import { Maybe, just, nil, nothing, or } from '@perfective/common/maybe';

const numbers: Maybe<number>[] = [
    just(2.71),
    just(3.14),
    nothing<number>(),
    nil<number>(),
];

numbers.map(or(0)) === [2.71, 3.14, 0, 0];
----


== Type classes

=== Monad

The `Maybe<T>` type is a monad that provides:

* the `Maybe.onto()` method as a _bind_ operator (`>>=`);
* the `just()` constructor as a _unit_ (`return`) function.

It satisfies the three https://wiki.haskell.org/Monad_laws[monad laws] for defined non-null `T`:

1. _unit_ is a left _identity_ for _bind_:
+
[source,typescript]
----
let x: T;
let f: (value: T) => Maybe<U>;

just(x).onto(f) === f(x);
----
+
2. _unit_ is a right _identity_ for _bind_:
+
[source,typescript]
----
let ma: Maybe<T>;

ma.onto(just) === ma;
----
+
3. _bind_ is associative:
+
[source,typescript]
----
let ma: Maybe<T>;
let f: (value: T) => Maybe<U>;
let g: (value: U) => Maybe<V>;

ma.onto(a => f(a).onto(g)) === ma.onto(f).onto(g)
----

[WARNING]
====
If you have a `flatMap` function with custom handling for `null` or `undefined` values,
you may break the _left-identity_ and the _associativity_ monad laws.
====

.Custom handling of `null` with `Maybe<T>.onto()` breaking the _left-identity_ law.
[source,typescript]
----
import { isNull } from '@perfective/common';
import { Just, just, nil } from '@perfective/common/maybe';

function decimal(value: number | null): Just<string> { // <.>
    if (isNull(value)) {
        return just('0');
    }
    return just(value.toString(10));
}

just(3.14).onto(decimal) == decimal(3.14); // <.>
nil().onto(decimal) != decimal(null); // <.>
----
<.> `Maybe<T>.onto()` expects the function of type `Unary<number, Maybe<string>>`,
but the `decimal` function is of type `Unary<number | null, Maybe<string>>`,
so the argument type does not match.
<.> Applying `decimal` to a present `number` behaves as expected.
<.> When the value is absent, `onto` does not execute `decimal` at all,
so the result is not the same as applying `decimal` directly.

If you have to use custom handling of `null`/`undefined`,
you should use the `Maybe.into()` method
that passed `null` and `undefined` as into the callback.

.Custom handling of `null` and `undefined`
[source,typescript]
----
import { isAbsent } from '@perfective/common';
import { Just, just, nothing, nil } from '@perfective/common/maybe';

function decimal(value: number | null | undefined): Just<string> {
    if (isAbsent(value)) {
        return just('0');
    }
    return just(value.toString(10));
}

just(3.14).onto(decimal) == decimal(3.14); // === just('3.14')
just(3.14).into(decimal) == decimal(3.14); // === just('3.14')

nothing().onto(decimal) == nothing(); // != decimal(undefined);
nothing().into(decimal) == decimal(undefined); // === just('0')

nil().onto(decimal) == nil(); // != decimal(null);
nil().into(decimal) == decimal(null); // === just('0')
----


For the (legacy) functions
(written prior to using `Maybe`)
that handle/return `null`/`undefined`,
you should use `Maybe.map()` or `Maybe.lift()` methods.


=== Functor

The `Maybe<T>` type is a functor that provides:

* the `Maybe.to()` method as a `fmap` operator.

It satisfies https://wiki.haskell.org/Functor[functor laws] for defined non-null `T`:

1. `Maybe.to()` preserves identity morphisms:
+
[source,typescript]
----
let id = (value: T) => value;
let value: T;

maybe(value).to(id) === maybe(id(value));
----
+
2. `Maybe.to()` preserves composition of morphisms:
+
[source,typescript]
----
let f: (value: U) => V;
let g: (value: T) => U;
let value: T;

maybe(value).to(v => f(g(v))) === maybe(value).to(g).to(f);
----
