= Perfective ESLint Config for Angular

`@perfective/eslint-config-angular` provides
a https://eslint.org/docs/developer-guide/shareable-configs[shareable ESLint configuration]
that is used for the development of the `@perfective` https://angular.io[Angular] packages.
This package extends the
`link:https://www.npmjs.com/package/@perfective/eslint-config[@perfective/eslint-config]` package.

`@perfective/eslint-config-angular` uses the following ESLint plugins:

* `link:https://github.com/angular-eslint/angular-eslint[@angular-eslint/eslint-plugin]`;
* `link:https://github.com/testing-library/eslint-plugin-jest-dom[eslint-plugin-jest-dom]`;
* `link:https://github.com/cartant/eslint-plugin-rxjs-angular[eslint-plugin-rxjs-angular]`;
* `link:https://github.com/testing-library/eslint-plugin-testing-library[eslint-plugin-testing-library]`.

== Setup

. Require `@perfective/eslint-config-angular` and its peer dependencies as dev dependencies:
+
[source,bash]
----
npm install --save-dev \
    @perfective/eslint-config-angular \
    @angular-eslint/eslint-plugin \
    @angular-eslint/eslint-plugin-template \
    @angular-eslint/template-parser \
    @typescript-eslint/eslint-plugin \
    @typescript-eslint/eslint-plugin-tslint \
    @typescript-eslint/parser \
    eslint \
    eslint-import-resolver-typescript \
    eslint-plugin-array-func \
    eslint-plugin-deprecation \
    eslint-plugin-eslint-comments \
    eslint-plugin-import \
    eslint-plugin-jest \
    eslint-plugin-jest-dom \
    eslint-plugin-jest-formatting \
    eslint-plugin-jsdoc \
    eslint-plugin-node \
    eslint-plugin-prefer-arrow \
    eslint-plugin-promise \
    eslint-plugin-rxjs \
    eslint-plugin-rxjs-angular \
    eslint-plugin-simple-import-sort \
    eslint-plugin-sonarjs \
    eslint-plugin-testing-library \
    eslint-plugin-unicorn \
    tslint \
    codelyzer
----
+
. Require the configuration in your root `.eslintrc.js` or `.eslintrc.json`.
+
[source,json]
----
{
    "extends": [
        "@perfective/eslint-config-angular"
    ]
}
----
+
[NOTE]
====
Use `@perfective/eslint-config-angular/community`,
based on the `@perfective/eslint-config/community`,
for a less strict configuration.
====
+
. Configure your `.eslintignore` file.

== TSLint

While the `link:https://github.com/angular-eslint/angular-eslint[@angular-eslint/eslint-plugin]` is
still in active development,
https://github.com/mgechev/codelyzer[Codelyzer] is used to increase the quality coverage.
It's based on the deprecated https://palantir.github.io/tslint/[TSLint].
TSLint rules are executed using the
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint[ESLint Plugin TSLint].

== Roadmap

* Remove TSLint and Codelyzer support.
