= Changelog

== v0.2.0 (next)

* Compiled `ES6` and `CommonsJS` modules.
* Added package documentation.
* Added types:
** `UnicodeNormalizationForm`,
** `UnicodeCanonicalEquivalenceNormalization`,
** `UnicodeCompatibilityNormalization`,
** `Replacement`,
** `Utf16CodeUnit`,
** `CodePoint`.
* Added functions and operators based on the `String` prototype: `charAt`, `charCodeAt`, `codePointAt`, `concat`
`endsWith`, `includes`, `indexOf`, `lastIndexOf`, `normalize`, `padEnd`, `padStart`, `repeat`, `replace`, `replaceWith`,
`search`, `slice`, `startsWith`.
* Added `length` function.
* Added support for `null` and `undefined` arguments in the `output` function.
* Added `isOutput/`isNotOutput` type guards.
* Added `lines` unit function.
* Removed unnecessary construction of unary functions: `lowerCase`, `upperCase`, `trim`.


== v0.1.0

* Declared the `Output` interface.
* Added the `output()` function.
* Added the `isString()`/`isNotString()` and `isEmpty()`/`isNotEmpty()` functions.
* Added the `lowerCase`/`upperCase()`, `split()`, and `trim()` functors.
