= Boolean

The `@perfective/common/boolean` package provides types and functions to work with the `boolean` type.


== Proposition

`Proposition<T>` is a `boolean` value,
or a nullary function that returns a `boolean` value.

* `isTrue(proposition: Proposition): boolean`
+
* `isFalse(proposition: Proposition): boolean`
+
* `negated(value: Proposition): boolean`
— negates the given proposition value.


== Predicate

`Predicate<T>` is a unary function that returns a `boolean` value.

* `is<T>(input: T): Predicate<T>`
— creates a `Predicate` that is `true` if its argument strictly equals a given `input`.
+
* `isNot<T>(input: T): Predicate<T>`
— creates a `Predicate` that is `true` if its argument does not equal a given `input`.
+
* `not<T>(predicate: Predicate<T>): Predicate<T>`
— creates a `Predicate` that inverses the result of a given `Predicate`.
+
* `all<T>(...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when all given `predicates` are `true` (logical `AND`).
+
* `either<T>(...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when at least one of given `predicates` is `true` (logical `OR`).
+
* `neither<T>(...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when none of given `predicates` is `true`.
+
* `atLeast<T>(minimum: number, ...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when at least a given `minimum` number of given `predicates` is true.
+
* `atMost<T>(maximum: number, ...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when no more than a given `maximum` number of given `predicates` is true.
+
* `exactly<T>(count: number, ...predicates: Predicate<T>[]): Predicate<T>`
— creates a `Predicate` that is `true` when exactly a given `count` number of given `predicates` is true.
