= Perfective Maybe (Monad)

`@perfective/maybe` package provides an https://en.wikipedia.org/wiki/Option_type[Option type] implementation.
It is inspired by the Haskell
`link:https://en.wikibooks.org/wiki/Haskell/Understanding_monads/Maybe[Maybe]` monad,
and is following the https://en.wikipedia.org/wiki/Monad_(functional_programming)#Analysis[monad laws]
as close as possible given the limitations of JavaScript and TypeScript
(exceptions and solutions are described below).

The purpose of the `Maybe` type is to simplify handling of values that may be absent
by providing operators that are called only when a value is present.
It allows creating chained calls similar to ones created by `Promise.then()` and RxJS `pipe()`
and handling values in-place.


== Installation

[source,bash]
----
npm install @perfective/maybe
----


== Implementation with `null` and `undefined`

In JavaScript there two different types representing "absence": `undefined` and `null`.
This means, that the standard dichotomy like `Just | Nothing`,
or `Some | None` does not fit precisely,
and requires additional logic to cover all the cases: `T | null | undefined`.
For example, when you create a new `Maybe<T>` with a `null` value,
it has to maintain this value as `null` and not switch it to `undefined`.

.`Maybe<T>` maintains the original value.
[source,typescript]
----
import { maybe, naught, nothing } from '@perfective/maybe';

maybe(undefined).value === undefined;
nothing().value === undefined; // <1>

maybe(null).value === null;
naught().value === null; // <2>

maybe(3.14).value === 3.14;
----
<1> The `nothing()` function is the default unit function for `Nothing<T>`
and returns a memoized `new Nothing(undefined)`.
<2> The `naught()` function is the secondary unit function for `Nothing<T>`
and returns a memoized `new Nothing(null)`.

It may not always be desired to have both `undefined` and `null` excluded.
Consider you have data coming from an API.
If this API has JSON schema attached
and that schema says that all fields will be returned,
it is not correct to treat them as `T | null | undefined`,
but rather only as `T | null`
(or even just `T`, if the field is required).
Using `maybe` will hide a problem with the API,
as a field that is not returned will be treated as if it was returned as `null`.
To handle such cases,
in addition to the `Maybe` type,
there are two other types:

* `Nullable<T>` that considers `null` as _absent_ and `undefined` as _present_:
** `Solum<T>` represents a present value;
** `Nil<T>` represents an absent value.
+
* `Optional<T>` that considers `undefined` as _absent_ and `null` as _present_:
** `Some<T>` represents a present value;
** `None<T>` represents an absent value.

The original value (`null` or `undefined`) will be preserved through operations.

.`nullable` maintains the original `null` value context.
[source,typescript]
----
import { just, nullable, optional } from '@perfective/maybe';
import { isGreaterThan } from '@perfective/real';

nullable(3.14)
    .that(isGreaterThan(4))
    .value === null;

optional(3.14)
    .that(isGreaterThan(4))
    .value === undefined;

just(3.14)
    .that(isGreaterThan(4))
    .value === undefined; // <1>

maybe(null)
    .that(isGreaterThan(4))
    .value === null; // <2>
----
<1> For the `Maybe<T>`, the default `Nothing` context is `undefined`,
so going from `Just` to `Nothing` will default to `undefined`.
<2> But if `Maybe` already is `Nothing`,
it will keep the original value.


== Maintaining the monad context

An important implementation detail of this package is a strict typing of the context.
It means, that if you know you a `Just` type, you don't lose this information.

.Difference between `Maybe`, `Just` and `Nothing` contexts.
----
function maybeDecimal(ma: Maybe<number>): Maybe<string> { // <.>
    return ma.to(a => a.toString(10));
}

function justDecimal(ma: Just<number>): Just<string> { // <.>
    return ma.to(a => a.toString(10));
}

function nothingDecimal(ma: Nothing<number>): Nothing<string> { // <.>
    return ma.to(a => a.toString(10));
}
----
<1> In the first example, the argument of the `maybeDecimal` function is only `Maybe<number>`.
It allows to pass either `Just<number>` or `Nothing<number>`.
As it's flexible for the function call (and is usually desired),
it limits the return type strictly to `Maybe<string>`.
The lambda `a => a.toString(10)` is guaranteed to be a string,
it may never be called, if `ma` is `Nothing`,
returning `Nothing` as the result.
<2> In case of the `justDecimal` function,
the argument is `Just<number>`,
so the bound value (inside the monad) is _always_ present.
Hence, given the lambda that also _always_ returns a value,
the result type can be narrowed down to a stricter `Just<string>`.
<3> If we decide to limit ourselves with `Nothing<number>` as an argument,
we won't be able to return anything but `Nothing<string>`.


== Usage

There are three distinct type groups that are available in this package:

* `Maybe<T>` is `Just<T>` or `Nothing<T>`;
* `Optional<T>` is `Some<T>` or `None<T>`;
* `Nullable<T>` is `Solum<T>` or `Nil<T>`.

The examples below are shown primarily for the `Maybe` type,
as its most used.


=== `onto(flatMap)`

`Maybe.onto()` is the _bind_ operator (`>>=`),
that (almost) satisfies three https://wiki.haskell.org/Monad_laws[monad laws]:

* _Unit_ is a _left-identity_ for _bind_:
+
[source,typescript]
----
let f: (value: T) => Maybe<U>;

maybe(x).onto(f) === f(x);
----
+
Given a function that map a given `value` into a `Maybe`,
applying it to a value through the `onto` operator
results in the same value,
as when function was applied directly.
+
* _Unit_ function is a _right-identity_ for _bind_:
+
[source,typescript]
----
let ma: Maybe<T>;

ma.onto(maybe) === ma;
----
+
Given a monad value,
applying a unit function through the `onto` operator
results in the same monad value.
+
* _Bind_ operator is associative
+
[source,typescript]
----
let ma: Maybe<T>;
let f: (value: T) => Maybe<U>;
let g: (value: U) => Maybe<V>;

ma.onto(a => f(a).onto(g)) === ma.onto(f).onto(g)
----
+
Given a monad value,
applying one function and then another inside one `onto`
is the same as applying those functions consequentially.
In other words, `onto` operators can be flattened.

[WARNING]
====
The _left-identity_ and _associativity_ laws are not satisfied
when the given function has custom handling
of `null` or `undefined` values.

If the result of the function is critical,
use the `Maybe.lift()` function as it executes the given function even when the value is absent.
====

.Consider an example function `decimal` that handles different cases that are possible in JS code.
[source,typescript]
----
import { isAbsent } from '@perfective/value';
import { Just, just, maybe, naught, nothing } from '@perfective/maybe';

function decimal(value?: number | null): Just<string> {
    if (isAbsent(value)) {
        return just('0');
    }
    return just(value.toString(10));
}

maybe(3.14).onto(decimal) == decimal(3.14); // <.>
maybe(0).onto(decimal) == decimal(0);
maybe(-1).onto(decimal) == decimal(-1);

nothing().onto(decimal) != decimal(undefined);
naught().onto(decimal) != decimal(null); // <.>
----
<1> Applying `decimal` to a present `number` satisfies the first law.
<2> When value is absent, `onto` does not execute `decimal` at all,
so the result is not the same, as by applying `decimal` directly.
The _left-identity law_ is *not* satisfied.

.Using `Maybe.lift` to handle functions with custom `null`/`undefined` handling.
[source,typescript]
----
import { isNull, isUndefined } from '@perfective/value';
import { Just, just, maybe, naught, nothing } from '@perfective/maybe';

function decimal(value?: number | null): string { // <.>
    if (isNull(value)) {
        return 'null';
    }
    if (isUndefined(value)) {
        return 'undefined';
    }
    return value.toString(10);
}

maybe(3.14).lift(decimal) == just('3.14'); // <.>

nothing().lift(decimal) === just(decimal(undefined));
naught().lift(decimal) === just(decimal(null)); // <.>
----
<1> `lift` is a `map` operator, not a `flatMap`,
so the function should transform value of type `T` into a value of type `U`.
`lift` itself will wrap it into the `Maybe<U>`.
<2> Applying the `decimal` function using `lift` returns the same result for a present value.
<3> But when we apply `decimal` function to `Nothing`,
`lift` operator is actually called,
and its result wrapped into `maybe` is returned.

[INFO]
====
This method is similar to the `mergeMap`/`switchMap` operator in `rxjs`
and the `flatMap` method in `java.util.Optional`.
====


=== `to(map)`

`Maybe.to()` is a mapping operator,
that applies the provided mapping function only when the value is present
and wraps up the result into a new `Maybe` value.

[IMPORTANT]
====
`Maybe.to` is not a _bind_ operator and is not required to satisfy the monad laws.
====

.Using `Maybe.to()` to chain computations
[source,typescript]
----
import { Maybe, maybe } from '@perfective/maybe';
import { lowercase } from '@perfective/string';

interface Name {
    first: string;
    last: string;
}

interface User {
    id?: number;
    name?: Name;
}

function nameOutput(name?: Name): string | undefined {
    return maybe(name)
        .to(name => `${name.first} ${name.last}`) // <.>
        .or(undefined);
}

function usernameOutput(user?: User): Maybe<string> {
    return maybe(user)
        .to(user => nameOutput(user.name)) // <.>
        .to(lowercase);
}
----
<1> Unlike `onto`, `to` should return an unpacked value.
The result will be wrapped into `maybe`
<2> This example can be simplified be using `Maybe.pick()`.

[INFO]
====
This method is similar to the `map` operator in `rxjs`
and the `map` method in `java.util.Optional`.
====


=== `pick(property)`

`Maybe.pick()` is a shortcut for the `Maybe.to()`
that allows to provide a property name to pick from an object.
Only properties that are defined on the value type are allowed.

It is similar to the
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#optional-chaining[optional chaining]
that was introduced in TypeScript 3.7,
but does not generate excessive JS code for each `null` and `undefined` check in the chain.

.Using `Maybe.pick()` for optional chaining
[source,typescript]
----
import { panic } from '@perfective/error';
import { maybe } from '@perfective/maybe';

interface Name {
    first?: string;
    last?: string;
}

interface User {
    id: number;
    name?: Name;
}

function firstName(user?: User): string {
    return maybe(user).pick('name').pick('first').or(panic('First name unknown')); // <.>
}

function userId(user: User): number {
    return just(user).pick('id').value; // <.>
}
----
<1> `maybe(user).pick('email')` will not compile,
as, in this example, the `User` type does not have an `email` property.
<2> When value is `Just` and a required property is picked,
the result is `Just<U>` (where `U` is the type of that property).
Hence, it's strongly recommended starting a `maybe`-chain with `Just`
if the value is already present.

[INFO]
====
This method is similar to the `pluck` operator in `rxjs`.
====


=== `that(filter)`

`Maybe.that()` is a filter method.
It allows to pass a predicate,
that will be used if the value is present.

.Using `Maybe.that()` to filter out a value
[source,typescript]
----
import { isNot } from '@perfective/fp';
import { Maybe, just } from '@perfective/maybe';

function quotient(dividend: number, divisor: number): Maybe<number> {
    return just(divisor)
        .that(isNot(0)) // <.>
        .to(divisor => dividend / divisor);
}
----
<1> Returns `Nothing`, so `to()` will not be running its function.

[INFO]
====
This method is similar to the `filter` operator in `rxjs`
and the `filter` method in `java.util.Optional`.
====


=== `which(filter)`

`Maybe.which()` is a filter method that requires to use a
link:https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types[_type guard_].
It handles the result type,
so it can be used inside the binding operators.

.Using `Maybe.which()` to filter out values with absent properties.
[source,typescript]
----
import { Maybe, just } from '@perfective/maybe';
import { hasDefinedProperty } from '@perfective/object';

interface Name {
    first: string;
    last: string;
}

interface Username {
    first?: string;
    middle?: string;
    last?: string;
}

function nameOutput(name: Name): string {
    return `${name.first} ${name.last}`;
}

function usernameOutput(user: User): Maybe<string> {
    return just(user)
        .which(hasDefinedProperty('first', 'last')) // <.>
        .to(nameOutput); // <.>
}
----
<1> A broader `hasPresentProperty('first', 'last')` can be used as well,
to guarantee that these properties _value_ are not `null` too.
It is not required for the TS compiler `strictNullCheck`,
as these properties only _optional_,
but are not _nullable_.
<2> `Name` type requires both `first` and `last` properties to be defined and not null,
so  without the `which` filter (with TS `strictNullChecks` enabled),
this code will not compile.


=== `when(condition)`

`Maybe.when()` is a filter method that allows to use a proposition
(a `boolean` value, or a nullary function that returns `boolean`)
to describe condition that is not related to the value inside `Maybe`.

[NOTE]
====
`Maybe.when()` should be used to increase readability,
as a nullary function can be passed into the `Maybe.that()`.
====

.Using `Maybe.when()` to filter out values based on a global condition.
[source,typescript]
----
import { just } from '@perfective/maybe';

function tokenLogOutput(token: string, isLog: boolean): Maybe<string> {
    return just(token)
        .when(isLog) // <.>
        .to(token => '***');
}
----
<1> Can be `when(() => isLog)`,
if we want to run computation only when the value is present.


=== `otherwise(fallback)`

`Maybe.otherwise()` method allows to provide a fallback value or to throw an error.

.Using `Maybe.otherwise()` to continue the chain after the fallback.
[source,typescript]
----
import { panic } from '@perfective/error';
import { isNot } from '@perfective/fp';
import { maybe } from '@perfective/maybe';

function range(min?: number, max?: number): number {
    return maybe(min)
        .otherwise(max) // <.>
        .that(isNot(0))
        .otherwise(panic('Invalid range'));
}
----
<.> `otherwise` wraps the fallback value into the next `Maybe`.


=== `or(fallback)`

`Maybe.or()` method allows to get the present value of the monad,
to fallback to the provided value if monad value is absent,
or to throw an error.

.Using `Maybe.or()`
[source,typescript]
----
import { panic } from '@perfective/error';
import { maybe } from '@perfective/maybe';

interface Name {
    first: string;
    last: string;
}

interface User {
    name?: Name;
}

function nameOutput(name?: Name): string {
    return maybe(name)
        .to(name => `${name.first} ${name.last}`)
        .or('Unknown name'); // <.>
}

function userOutput(user?: User): string {
    return maybe(user)
        .pick('name')
        .to(nameOutput)
        .or(panic('Undefined user')); // <.>
}
----
<1> The fallback value type can be present or absent.
It allows to always return only `undefined` or `null` if the value is absent.
<2> Using `panic` or any other function that throws an error when called
allows to guarantee a present value is returned.

[INFO]
====
This method is similar to the `orElse`, `orElseGet`, and `orElseThrow` methods in `java.util.Optional`.
====


=== `run(procedure)`

`Maybe.run()` method allows to run a procedure with the present value.
It always returns the original value
(or a reference to the original object,
which can be mutated by the procedure).

[NOTE]
====
This method is similar to the `tap` operator in `rxjs`
and `ifPresent` method in `java.util.Optional`.
====


=== `lift(map)`

`Maybe.lift()` method allows to pass a function that maps the value even when it is absent.
It always runs, unlike `Maybe.map()` that is called only when the value is present.

[source,typescript]
----
import { isAbsent } from '@perfective/value';
import { maybe } from '@perfective/maybe';

function decimal(value?: number | null): string {
    if (isAbsent(value)) {
        return '0';
    }
    return value.toString(10);
}

maybe(undefined).lift(decimal) === just(decimal(undefined));
maybe(null).lift(decimal) === just(decimal(null)); // <.>
----
<1> `Maybe.lift()` wraps the result into the next `maybe` value.


=== Lifting functions

Each method has a corresponding lifting function that can be used in the `Array.prototype.map`
(or any other mapping method or operator).

[source,typescript]
----
import { Maybe, just, naught, nothing, or } from '@perfective/maybe';

const numbers: Maybe<number>[] = [
    just(2.71),
    just(3.14),
    nothing<number>(),
    naught<number>(),
];

numbers.map(or(0)) === [2.71, 3.14, 0, 0];
----

[WARNING]
====
As of v0.6.0, lifting functions only supported for the `Maybe`/`Just`/`Nothing` types,
and are not supported for `Nullable`/`Solum`/`Nil` or `Optional`/`Some`/`None`.
====
