= Promise

The `@perfective/common/promise` package provides functions to work with the
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` class.

== Reference

=== Types

* `type Resolvable<T> = T | PromiseLike<T>`
— a shortcut for a type of values that can be passed into `Promise.resolve()`.
+
* `type Resolve<T> = (value: Resolvable<T>) => void`
— a type of a callback called to resolve a `Promise` value.
+
* `type Reject<E extends Error = Error> = (reason?: E) => void`
— a type of a callback called to reject a `Promise` with a `reason`.
+
[NOTE]
====
This type is stricter than the default type of the reject callback,
as it requires an `Error` as a `reason`.
====
+
* `type Executor<T, E extends Error = Error> = (resolve: Resolve<T>, reject: Reject<E>) => void`
— a type of the `executor` callback passed into a `Promise` constructor.
+
* `type OnFulfilled<T, U = T> = (value: T) => Resolvable<U>`
— a type of a callback passed as `onFulfilled` into `Promise.then()`.
+
* `type OnRejected<T = never> = (reason: unknown) => Resolvable<T>`
— a type of a callback passed as `onRejected` into `Promise.then()` or `Promise.catch()`.
+
* `type Callback<T, E extends Error = Error> = (error: E | null | undefined, value: T) => void`
— a type of the error-first callbacks.


=== Constructors

* `async function promise<T, E extends Error = Error>(executor: Executor<T, E>): Promise<T>`
— creates a new `Promise` with a given `executor` callback.
+
* `async function fulfilled<T>(value: Resolvable<T>): Promise<Awaited<T>>`
— creates a fulfilled `Promise` (a shortcut for the `Promise.resolve()` function).
+
[NOTE]
====
Using `Promise.resolve()` directly causes the `@typescript-eslint/unbound-method` linting error
and a TS compiler error: `TS2322: Type 'unknown' is not assignable to type 'T'`.
====
+
* `async function rejected<T = never>(reason: Error): Promise<Awaited<T>>`
— creates a rejected `Promise` (a shortcut for the `Promise.rejected()` function).
+
[NOTE]
====
Using `Promise.rejected()` directly causes the `@typescript-eslint/unbound-method` linting error.
====
+
* `settled<T>(): BiFold<Resolvable<T>, Error, Promise<Awaited<T>>>`
— creates a `BiFold` pair of callbacks to wrap a value into a `Promise`.
+
* `function settlement<T, E extends Error = Error>(resolve: Resolve<T>, reject: Reject<E>): Callback<T, E>`
— create a `Callback` that uses given `resolve` and `reject` functions from an `executor` to settle a `Promise`.
Use `settlement` to promisify functions written in the error-first callback style.
