= Math

The `@perfective/common/math` package provides functions built around the global
`link:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math[Math]` object.
It also provides additional mathematical abstractions that may be useful in development.


== Arithmetic functions

* `sum(augend: number, addend: number): number`
* `difference(minuend: number, subtrahend: number): number`
* `product(multiplier: number, multiplicand: number): number`
* `quotient(dividend: number, divisor: number): number`
* `remainder(dividend: number, divisor: number): number`


== Set functions

* `maximum(values: readonly number[]): number | null`
— returns the maximum number if array contains numbers, `null` otherwise.
* `minimum(values: readonly number[]): number | null`
— returns the minimum number if array contains numbers, `null` otherwise.


== Interval

`Interval` represents a https://en.wikipedia.org/wiki/Interval_(mathematics)[real interval] range.

* Unit functions:
** `interval(min: number, max: number): Interval | null`
— returns an `Interval` when `min <= max`.
** `intervalFromPair(pair: readonly [number, number]): Interval | null`
— returns an `Interval` for an ordered pair.
** `intervalFromValues(values: number[]): Interval | null`
— returns an `Interval` for a non-empty array.
** `intervalFromNullable(min: number | null, max: number | null): Interval | null`
— returns an `Interval` from nullable values, replacing them with `-Infinity` and `Infinity`;
returns `null` if `min > max`.
+
* Predicates:
** `isInInterval(interval: Interval): Predicate<number>`
— returns a predicate to check if a number is in a closed interval.
** `isInOpenInterval(interval: Interval): Predicate<number>`
— returns a predicate to check if a number is in an open interval.
** `isInLeftOpenInterval(interval: Interval): Predicate<number>`
— returns a predicate to check if a number is in a left-open (and right-closed) interval.
** `isInRightOpenInterval(interval: Interval): Predicate<number>`
— returns a predicate to check if a number is in a right-open (and left-closed) interval.


== Roadmap

* `Interval`:
** `midpoint()`;
** `radius()`;
** `size`;
** `isSubInterval()`;
** `isStrictSubInterval()`.
** verify correct behavior with `Infinity`.
** consider adding negated functions, like `isNotInInterval()`.
