= Value

The `@perfective/value` package provides functions to work with `undefined` and `null` values
and utility types
(similar to `link:https://www.typescriptlang.org/docs/handbook/utility-types.html#nonnullablet[NonNullable<T>]`)
to describe some of such values.

== Utility types

* `type Defined<T> = T extends undefined ? never : T`
* `type NotNull<T> = T extends null ? never : T`
* `type Present<T> = T extends null | undefined ? never : T`
* `type Absent<T> = T extends null | undefined ? T : never`


== Type Guards

* `isDefined<T>(value: T | undefined): value is T`
* `isUndefined<T>(value: T | undefined): value is undefined`
* `isNotNull<T>(value: T | null): value is T`
* `isNull<T>(value: T | null): value is null`
* `isPresent<T>(value: T | null | undefined): value is T`
* `isAbsent<T>(value: T | null | undefined): value is null | undefined`

[NOTE]
====
`isDefined` and `isUndefined` use the same check against `void 0`
as the JS code generated by TypeScript for the
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining[optional chaining],
while TS compiler keeps checks `typeof value === 'undefined'` and `value === undefined` as is.
====

== Type Of

`TypeOf` is an extended type for the `typeof` operator to distinguish `null` and `array` from the `object` type.
`TypeOf` can be `undefined`, `null`, `boolean`, `number`, `bigint`, `string`, `symbol`, `function`, `array`,
or `object`.

* `typeOf<T>(value: T | null | undefined): TypeOf`.


== Handling `void`

In TypeScript, `link:https://www.typescriptlang.org/docs/handbook/basic-types.html#void[void]` type
is treated differently from `undefined` and `null`,
and linters provide different rules to restrict its usage only to correct cases.

Unfortunately, different packages (like AWS SDK) may use `void` as a synonym to `null | undefined`.
This approach creates conflicts in the code linted with the
`link:https://github.com/perfective/js/tree/master/packages/eslint-config[@perfective/eslint-config]`,
so a special function is introduced to "type cast" any `void` value into `null | undefined`:

* `voidable<T>(value: T | void): T | null | undefined`
